//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ross
    {
        public int ross_ID { get; set; }
        public string friendofross { get; set; }
        public string place { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
    }
}
