//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p.parcial1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ross
    {
        [Key]
        public int ross_ID { get; set; }
        [Required][Display(Name ="Nombre Completo")][StringLength(24,MinimumLength =2)]
        public string friendofross { get; set; }
        [Required]
        public string place { get; set; }
        [EmailAddress][Display(Name="Ingrese correo valido")]
        public string email { get; set; }
        [Display(Name ="Cumpleaños")]
        public Nullable<System.DateTime> birthdate { get; set; }
    }
}
